### PR TITLE
fix(1.7.3): handle completed projects

### LINKED ISSUE #130: [BUG] progress state does not update on landing page
Currently, progress is only updated when the webpage is refreshed.

### LINKED ISSUE #167: current lesson goes passed existing lessons after finishing a project
After I complete a project, I click the title to go back to the main page - the projects.json config now shows I'm on step 95, but there's only 94 steps:
Screen Shot 2022-11-30 at 9 01 36 PM
So if I click on that project again, it can't find that step and it crashes.

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #130 
Closes #167 

This:
1) Causes Camper to navigate back to landing page once the final lesson is completed
2) Fixes the issue where the landing page project info is not updated (lessons complete)

### CODE REVIEW

**Review by moT01 — COMMENTED** [review]
Doesn't the package-lock need updating here @ShaunSHamilton?

**Comment by ShaunSHamilton** [comment]
> Doesn't the package-lock need updating here @ShaunSHamilton?

Maybe 👀

**Comment by moT01** [comment]
I made a few changes, want to take a quick look when you get a chance @ShaunSHamilton?

**Review by ShaunSHamilton — COMMENTED** [review]
Very nice checkmark, Tom 👍

**Pull request merged**
